### ISSUE TITLE
Users in groups not being notified

### ISSUE THREAD

**Issue by tankerkiller125** [FriendsOfFlarum/byobu#109]
When a user is in a group that's part of a PM but not actually listed a user part of the discussion they don't seem to receive the web notifications/emails about new post/replies.

Originally this worked properly in an older version but it seems to be broken on the latest release.

Update: I disabled and re-enabled notifications and it seems to be working properly again. Feel free to close this issue if it's consider a one time glitch.

**Comment by imorland** [comment]
@tankerkiller125 can you please confirm if this is still resolved for you? If so, I'll close this issue

**Comment by tankerkiller125** [comment]
It seems to be fixed now, I'm not sure exactly what originally happened or why I had to reset my notifications but all seems good now.

**Comment by imorland** [comment]
Ok, great - thanks!
