### ISSUE TITLE
Duplicate PM notifications

### ISSUE THREAD

**Issue by bmcd243** [FriendsOfFlarum/byobu#114]
When you got a PM response, you get two notifications which is quite annoying...

1. [membername] replied to your post
2. [membername] replied in a private discussion that you're apart of

Surely there is only need for one.

**Comment by imorland** [comment]
This _should_ now be addressed, thanks for raising it! I'll close this issue now, but feel free to re-open after checking out the new release if you still have issues!

**Comment by bmcd243** [comment]
Cheers Ian!
