### ISSUE TITLE
Bazaar has been abandoned

### ISSUE THREAD

**Issue by streaps** [FriendsOfFlarum/byobu#127]
“As I will soon deprecate the flagrow.io API Bazaar will also stop working. As such this discussion will now be marked incompatible.”
https://discuss.flarum.org/d/5151-bazaar-the-extension-marketplace/267

“Bazaar has now been abandoned. I recommend you to use composer directly.”
https://discuss.flarum.org/d/5151-bazaar-the-extension-marketplace/273

Should Bazaar be removed from the README?

**Comment by clarkwinkelmann** [comment]
There are many READMEs to update, not just this one :sweat_smile: 

I have updated the Bazaar discussion on Discuss to remove the installation command, that way people who don't see the "incompatible" tag won't install Bazaar by mistake.

**Comment by streaps** [comment]
> There are many READMEs to update, not just this one 😅

I realized that after I posted the issue :). 

I indeed didn't see the 'incompatible' tag first. Thank you for updating the discussion.

**Comment by luceos** [comment]
My apologies for any inconvenience. @datitisev has been trying desperately to get bazaar back online using the extiverse backend, but so far he has ran into more issues than one can hope for.

In the meantime the successor functionality baked into extiverse is moving forward nicely. My plan is to offer the ability to configure a list of extensions and then deploy these for installation or upgrading through FTP or SSH.
