### ISSUE TITLE
Suggestion: ability to customize FA icon

### ISSUE THREAD

**Issue by sburkett** [FriendsOfFlarum/byobu#135]
A lot of other extensions allow you to customize the FontAwesome icon used for various things. From the looks of things, the `fa-map` is hardcoded into all of the .js for this extension. And the map icon, well ... looks like a folded map, and not like something that would easily be associated with a private conversation. 

Yes, I could just modify all of the .js, but that is a breaker obviously. It would be nice to add this to the settings for this extension as well. :)

**Comment by clarkwinkelmann** [comment]
Multiple extensions allow customizing icons that are saved alongside specific records in the database, like Tags, Mason fields, Masquerade fields, ...

But extensions usually don't allow customizing icons used by static buttons, like Byobu, User directory, Tags, Categories, ...

These icons can be replaced relatively easily with custom CSS. As such, I don't think it makes sense to provide a setting for it.

We're not against a suggestion to change the default icon to something more appropriate though :)

The choice to use the map FA icon is linked to Byobu [meaning](https://en.wikipedia.org/wiki/By%C5%8Dbu) "folding screens" and the map FA icon was the closest to Byobu extension icon.

**Comment by sburkett** [comment]
Respectfully, visitors to forums likely have no idea what a byōbu is. So the folding screen (fa-map) icon just doesn't add much value to the experience, in my view. Instead of hardcoding it to something else, it would be so much simplerto just add a config field for it.

More configurability means better software, especially when it comes to cosmetics.

Yes, some shifty .CSS and/or .JS can get the job done. I'm a dev, it doesn't bother me. But those kinds of modifications take away from the beauty of using something is configurable. Quick. Easy. Asking someone who wants to throw up a forum that they have to write a mutation observer in Javascript or use .css positioning and pseudo elements to replace something like an icon just seems silly. That's the vBulletin world :)

Just a few thoughts.

**Comment by imorland** [comment]
Sorry for the delay @sburkett 

I'm happy to say that this suggestion will be included in the upcoming update of this extension for Flarum beta 15. Here's a preview:
![image](https://user-images.githubusercontent.com/16573496/102699786-67fdef00-423f-11eb-8785-c437ec701301.png)
