### ISSUE TITLE
Users can't send DM to users

### ISSUE THREAD

**Issue by arteteco** [FriendsOfFlarum/byobu#137]
Hello everyone, I run a flrum forum on freeflarum.
The problem I'm having is this: 
* When a user creates a message and search for another user as recipient, list is empty and can't send it to anyone. They can see groups though
* admin/mod can send DMs to anyone, but those users can't reply: the field is like, fake, I can't write just select the text "write your answer here". Of course pressing the "Reply" button is no use
* Permissions seem ok. I tried playing around with them, but they should work, they used to work before the upgrade to 0.14.1

Let me know if I can give more useful information, thanks!

A screenshot of permissions: 
![permissions](https://i.imgur.com/Somwmtt.png)

What a user sees when trying to reply

![fake](https://user-images.githubusercontent.com/39224568/101521442-24290100-3986-11eb-8afe-2a7934070e0a.png)

**Comment by EvilExecutor** [comment]
Hello!

Thanks for reporting this issue. The new version of FriendsOfFlarum/byobu which will be released soon will have these problems fixed. If you face this problem again feel free to re-open!
