### ISSUE TITLE
Beta 16+ issues

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/byobu#145]
- [ ] All PD's show up to members, even those they aren't a recipient of
- [x] No PD's show up when flarum/approval is enabled
- [ ] Unified index choice doesn't matter. Discussion index always shows all dicussions, including private ones.

Some decisions to be made:

- [ ] drop unified index logic and go towards full no tags + separate list, this would probably require better updating of notification bell for byobu and/or updated count on left hand menu

**Comment by davwheat** [comment]
I think this is out of date now as Byobu has updated for 1.0
