### ISSUE TITLE
Tags went off hot -  its no longer useable

### ISSUE THREAD

**Issue by sibidharan** [FriendsOfFlarum/byobu#158]
## Feature Request

fof/byobu has support for tags previously. I was relying on that to sort thousands of private discussions under tags. This is a research institute and student post private discussions under lot of tags, so that it will be easy for them to track them. It will only appear under that particular tag, so it was very easy for everyone to maintain a coordination. 

But since the feature is removed now, all our discussions are assorted and we have no way of tracking what is happenning where. If you could give us an option to have tags or not have tags, it will be easy! Atleast give us some way of bringing that feature for required users from admin panel.

**Describe alternatives you've considered**

For now, we are making a post with index of links under tags to help the community know what is happenning around. But we cannot keep doing that. Please

**Comment by clarkwinkelmann** [comment]
Unfortunately this is not a use case we support anymore.

Byobu had to be simplified to survive, the reasons are explained here https://discuss.flarum.org/d/4762-friendsofflarum-by-bu-well-integrated-advanced-private-discussions/891

You are of course free to fork the older version to update it, or fork the current version and re-introduce the feature.
