### ISSUE TITLE
Can't update from 1.3.1 to 1.3.6

### ISSUE THREAD

**Issue by tutle** [FriendsOfFlarum/byobu#198]
Hello
I'm running flarum 1.8.5 on a yunohost server 11.2.27
the extension byobu is 1.3.1 and I can't upgrade to 1.3.6
I don't know how to solve it.
Sincerely

**Comment by clarkwinkelmann** [comment]
What have you tried? What happens?

What's the output of `composer require fof/byobu:"^1.3.6" --dry-run` (in the Flarum directory)?

**Comment by tutle** [comment]
output is
 [InvalidArgumentException]
  Package fof/byobu at version ^1.3.6 has a PHP requirement incompatible with
   your PHP version, PHP extensions and Composer version

**Comment by clarkwinkelmann** [comment]
The latest version of the extension requires PHP 8.0. You should upgrade, as 7.x is no longer supported by PHP anyway.

If you have a managed hosting, there are usually 2 different PHP settings, one for the webserver and one for the command line. Make sure both are set to the same version.

**Comment by tutle** [comment]
Finally solved with a few operations.
I had a Yunohost update incomplete, I made

```
    sudo apt install --fix-broken
    sudo apt autoremove
```
    then I was able to upgrade flarum to 1.8.5 with good php 8.4 (it was in 1.8.5 with php 7.4.33) directly from yunohost web admin, then update fof plugins directly in flarum with the plugin “extension manager”.
