### ISSUE TITLE
Adding / Removing Recipients Possible only by Admins

### ISSUE THREAD

**Issue by pflstr** [FriendsOfFlarum/byobu#36]
As reported [here](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/179) by Apoculos, only admins are able to add/remove users/groups to private discussions regardless how the permissions are setup. This issue is [still present](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/193) after updating to beta 7.

**Comment by clarkwinkelmann** [comment]
Actually still broken.

The issue is the prefix `discussion.` that must be removed on both permission checks at https://github.com/FriendsOfFlarum/byobu/blob/ed86443463fbe459f687598501316515b9130bda/src/Listeners/SaveRecipientsToDatabase.php#L110

**Comment by imorland** [comment]
No longer an issue due to permission changes and not requiring tags anymore
