### ISSUE TITLE
Permission configured per tag doesn't work

### ISSUE THREAD

**Issue by pflstr** [FriendsOfFlarum/byobu#39]
The new feature [Permission can now be configured per tag](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/200) doesn't seem to be working as intended.

I tried to set my permissions in a way, that private discussions are restricted to a specific tag (lets call it ``private``). I tried those two options:

a) Restrict privat discussions globally and allow it individually for the ``private`` tag.

b) Allow privat discussions globally and restrict it individually for all but the ``private`` tag.

Option a) seems to me the most intuitive way to do it, but neither a) nor b) achieves what I want. In both cases, the global setting overrides the tag setting leaving privat messages generally disallowed in a) and allowed in b), the tag doesn't make a difference.

An issue with the core seems related to this observation: https://github.com/flarum/core/issues/1146

What I would like to see in a perfect world (in my case scenario) is the following:

When a user starts a new Discussion and selects a tag differently from ``private``, the recipients selector should be greyed out. If he selects recipients first (also in the case of the link from the usercard), the tag input should only allow ``private`` (or the tag should be selected automatically).

One thing, I didn't make up my mind about yet: If a user selects two tags, one with the permission to open a private discussion, one that doesn't allow it, which setting should precede?

**Comment by luceos** [comment]
Can you make a distinction between:

1. Primary tags
2. Secondary tags
3. Helper tags (that's what I call secondary not under any primary)

That clarification might help me understand your situation better.

**Comment by pflstr** [comment]
That's interesting.

Case 2 doesn't make a difference compared to 1. Case 3 however ist different. I made ``private`` a helper tag und followed the Route a) of my initial report:

a) Restrict privat discussions globally and allow it individually for the ``private`` tag.

Unfortunately I now have to select another (primary) tag as well defeating my intended use case. But apart from that, this setup allowed to open a private discussion and thus overrule the global rule.

Which as well gives an answer to my last thougth in my initial report. If two tags are selected, one allowing private discussions and one forbidding them, allowance will be granted.

**Comment by pflstr** [comment]
Sorry, I have to correct myself. Case 3 is not different at all. My false impression resulted from myself acting as admin, who obviously couldn't be restricted globally. As a normal user I was not able to open a private discussion in the described way, with or without the ``private`` tag, from the ``Start a new Discussion`` as well as from the usercard.

So, there is no indication, that the global setting could be overruled by a helper tag.

**Comment by glowingblue** [comment]
Any news on this, we are facing the same issue!

**Comment by luceos** [comment]
@glowingblue not yet, I haven't been able to look into it. Any further investigation might help solve this sooner. I'm a little stuck with other responsibilities, but once Flarum beta 8 is out all Flagrow extensions will be revisited and bugs/features taken care of. Byobu will be one of the first.

**Comment by imorland** [comment]
Closing this now as byobu no longer uses tags in any way
