### ISSUE TITLE
Private Discussions show-up in the All Tags page (screenshot)

### ISSUE THREAD

**Issue by bikepost** [FriendsOfFlarum/byobu#44]
I just found out that if I click Tags on my main discussion Flarum page, I see Private Discussions previews without being signed-in.

![screen shot 2017-08-12 at 12 16 13](https://user-images.githubusercontent.com/30053780/29243628-86e85ee4-7f58-11e7-9b49-63fa8033704a.png)

In my screenshot:

- Under Announcement "Testing PM function"
- Under Approved Vendors "Hi Tyler Your account...."

When I click them I get the "You don't have permission...." error message.

They should not show up unless I am a party to the Private Discussions under the current extension developer's intent.

**Comment by Ralkage** [comment]
@bikepost this is no longer an issue as I have tested this locally as well as there was a fix put in for Beta 8 (which this extension has already been updated to). See: https://github.com/flarum/core/issues/1249

Closing this issue :)
