### ISSUE TITLE
Recipients not cleared after starting a private discussion

### ISSUE THREAD

**Issue by pflstr** [FriendsOfFlarum/byobu#48]
After starting a private discussion via the `send userXYZ a message` link on his UserPage, every attempt to start a new new discussion will preselect the previously selected users until the page is reloaded.

The bug can be easily reproduced at DevFlarum:

- Go to a users userpage
- Start a private discussion with him (opening the composer window suffices)
- Start another discussion anywhere
- Reload the page
- Start another discussion again

At stage 3, two recipients are preselected, at stage 5 they disappeared.

**Comment by glowingblue** [comment]
This looks like an issue with caching, after clearing the flarum cache the persistent recipients are gone again. Is it possible to clear just parts of the cache (in that case the post editor)?

**Comment by luceos** [comment]
This is a frontend thing. The frontend remembers the set recipients. Somehow it needs to clear the recipient list when on a new page. I'll have to look into this.

**Comment by glowingblue** [comment]
@luceos Any news for this issue ?

**Comment by luceos** [comment]
@glowingblue haven't looked into this yet
