### ISSUE TITLE
Wrong reply count

### ISSUE THREAD

**Issue by pflstr** [FriendsOfFlarum/byobu#51]
The reply count of private discussions is wrong beyond the original post, it shows 1 post less than there are: Only original post shows (0) replies, after first reply it's still (0), after second reply (1) etc.

This behaviour can be reproduced at the Devflarum sandbox server.

Whether this issue is related to https://github.com/flagrow/byobu/issues/50, I don't know.

**Comment by Ralkage** [comment]
I am unable to reproduce this issue as this has aged and beta 8 fixed a lot of these issues,

@pflstr if this is still happening even in your own install, feel free to reply and I'll reopen this issue if this is still an issue for you.
