### ISSUE TITLE
Can't transform PMs into public discussions

### ISSUE THREAD

**Issue by ardacebi** [FriendsOfFlarum/byobu#56]
Hello,

I was trying to transform PMs to public discussions by removing participants.

But I'm not able to. See this gif:

![video](https://user-images.githubusercontent.com/17576065/37784035-ffe861f0-2e07-11e8-9b0b-314ead8917e2.gif)

**Comment by Eldenroot** [comment]
Better to add a new button - make it public :)

**Comment by TurboProgramming** [comment]
@luceos

**Comment by luceos** [comment]
Thanks, I remember this worked in the past. But as we're not testing any of our extensions functionality might have been lost somewhere. I'll look into it, thanks for the report.

**Comment by TurboProgramming** [comment]
@luceos You're welcome, do you have any updates regarding it?

**Comment by luceos** [comment]
@TurboProgramming nope. My efforts are currently required elsewhere. I'll squeeze it in if possible, otherwise feel free to PR.

**Comment by Ralkage** [comment]
@luceos I was able to reproduce this in Beta 8 now as I assume this issue was created originally for Beta 7?

**Comment by CNFlarum** [comment]
We still need Public button in beta.12...

**Comment by imorland** [comment]
I'm working on this at the moment actually. It will be part of the next release :)
