### ISSUE TITLE
check permission before adding user to private discussion

### ISSUE THREAD

**Issue by manurohr** [FriendsOfFlarum/byobu#58]
When I have a discussion which is restricted to only moderator and would like to add a member, I should only see members who are allowed to read this post. I was able to add any other members who were not moderator. However this invited member was not able to see any private discussion because the member had no rights for this category.

Maybe it would be good if members, who have no rights, could be greyed out in the list as information that those members cannot participate in the discussion until they get the right permissions for this discussion/category.

**Comment by luceos** [comment]
Oh, never replied to this; but this makes sense. I'm unsure this is a bug or an improvement. Byobu plays an odd role integrated in Flarum the way it does.

**Comment by pflstr** [comment]
In a similar way, there should be checks before the change of assigned tags, whether all participants still meet the associated permissions.

**Comment by iPurpl3x** [comment]
@luceos or @imorland I think this can be closed, as Byobu doesn't function with tags anymore.
