### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by ardacebi** [FriendsOfFlarum/byobu#59]
![screenshot_2018-07-03 splash community](https://user-images.githubusercontent.com/17576065/42243688-d3ad6f5e-7f1a-11e8-98a2-2ccb4b579874.png)

Can you leave a space from the right of the textbox?

**Comment by TurboProgramming** [comment]
@luceos, I'll try fixing it, let me figure out what's the problem first of all :)

**Comment by Ralkage** [comment]
This was resolved and fixed with #60.

@luceos going to go ahead and closed this issue.
