### ISSUE TITLE
Text input broken on Firefox Mobile after enabling this

### ISSUE THREAD

**Issue by poVoq** [FriendsOfFlarum/byobu#63]
if I enable this plugin, the text field to enter a new discussion or reply to a discussion is somewhat broken with Firefox Android. You can still type somewhat, but when the onscreen keyboard is up you cant see what you are typing and the overall layout of the text editor is just broken.

**Comment by poVoq** [comment]
![screenshot_firefox_20180928-001644](https://user-images.githubusercontent.com/940360/46166572-55411d80-c2b5-11e8-898f-8e44b733eb03.png)
This is what it looks like on my forum.

**Comment by luceos** [comment]
This could well be an issue with Flarum in itself. I'm not taking action until beta 8 is released. The extension needs to be checked for consistency anyway.
