### ISSUE TITLE
Flagged post

### ISSUE THREAD

**Issue by ondrej2004** [FriendsOfFlarum/byobu#68]
One member flagged a post in a PM. But as Admin nor moderators are involved in the discussion they cannot take action therefor inappropriate comment is still there!

**Comment by ondrej2004** [comment]
Can SOMEONE HELP?????

**Comment by luceos** [comment]
Can you provide some additional information? What permission groups are attached to the discussion, how many users are involved, which post is flagged (the first, last etc)? Screenshot perhaps..

**Comment by PeopleInside** [comment]
Hi @ondrej2004 you mean if normal user are allowed to send a message to another normal user b and one of this two flag a message, moderators and admin are unable to read the message and take actions?

This can be a real issue.
Also admin cannot delete private message of users if user request so but maybe if the moderation issue will be fixed (never tested) user can report post that want to be removed.

**Comment by ondrej2004** [comment]
Well, mod nor admin can delete or preform action on posts in message. Not
sure why.
Thanks for answering

**Comment by PeopleInside** [comment]
This issue is not resolved and is present.
I tested now message from user A to user B (normal users).
User B report the private message of user A. Moderators admin see the report but when click the post for moderate have not access.

**Comment by luceos** [comment]
Thanks for confirming.

**Comment by ondrej2004** [comment]
No problem. Thanks ☺️

**Comment by ondrej2004** [comment]
Will this be resolved? I just got reminded today when it happened.
thanks

**Comment by luceos** [comment]
Sadly I'm tight up with other obligations right now. Would anyone be able to provide a pr maybe?

**Comment by imorland** [comment]
Hey @ondrej2004 FYI, I’ve today opened a PR that addresses this issue. Sorry it’s taken a while!

**Comment by ondrej2004** [comment]
> Hey @ondrej2004 FYI, I’ve today opened a PR that addresses this issue. Sorry it’s taken a while!

Thanks so much 😊
