### ISSUE TITLE
Require login to view the private discussion.

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/byobu#69]
If the user are not logged into the community and click the mention link will see page not found as link not valid. Will be maybe great to have a different situation require a login and maybe display a different error message if the account has no right to access the private message (maybe because wrong account).

The scenario:

- Admin or User A send a private message to User B
- User B receive the email notification and is not logged into the community
- User B follow the link and no page found is showed.

What user should see is a login page or a message that inform must be logged or have permission for see this private discussion.

**Comment by davwheat** [comment]
This has caught me out several times! I think it'd be a fantastic idea. PHP isn't my sort of thing, though, so I can't implement it 😂

**Comment by DavideIadeluca** [comment]
Thanks @PeopleInside for your suggestion. The scenario you are describing is a common pain point until today, but it's not limited to `fof/byobu`. Changing the behaviour of this requires rather significant changes in `flarum/core`. The core developers of Flarum are aware of this issue, and it may be considered for 2.x. 

In any case, I would suggest you open a new issue in https://github.com/flarum/framework or perhaps create a new proposal at https://discuss.flarum.org/t/proposals. Therefore, I will close this issue right here.
