### ISSUE TITLE
Titles of private discussion show in public tag overview

### ISSUE THREAD

**Issue by ajvdeutekom** [FriendsOfFlarum/byobu#74]
The tag overview page  (eg. https://discuss.flarum.org/tags) shows for every tag the latest post. 

These include titles of private discussions in which the user doesn't participate.

**Comment by luceos** [comment]
Tags extension has to take private discussions into account https://github.com/flarum/tags/blob/master/src/Listener/UpdateTagMetadata.php

**Comment by askvortsov1** [comment]
This can now be closed

**Comment by clarkwinkelmann** [comment]
Should be fixed with Flarum beta 14 (to be released in about a month). If anyone continues experiencing the issue once they upgrade to beta 14, let us know and we'll re-open.
