### ISSUE TITLE
Can't send a PM directly from user page

### ISSUE THREAD

**Issue by jordanjay29** [FriendsOfFlarum/byobu#78]
This appears to be a regression from an earlier version of Byobu, there was an action on the user Controls menu to send a PM directly from the user's page. Now it appears that the action item is missing: 

![image depicting the lack of PM option on user controls menu](https://i.imgur.com/srZqTjD.png)

**Comment by imorland** [comment]
Does the logged in user have admin or mod permissions? We are seeing that the sending a PM is missing from the drop down in those cases, but for regular users the option is still there

**Comment by jordanjay29** [comment]
Screenshot is from an admin user.
