### ISSUE TITLE
Byobu and Flagrow Upload don't seem to work well together with pasted images

### ISSUE THREAD

**Issue by AmauryCarrade** [FriendsOfFlarum/byobu#79]
Hi,

On my beta-10 forum, I'm using Flagrow Upload and Byobu. I found an odd bug: after one try to paste an image onto a post _on a private discussion_, he/she is redirected to what seems to be it last public post seen, and then pasting images cease to work on all composers (including public ones).

Upload from the button still works.

I don't really know where to send the ticket, here or on flagrow/upload, so I'm trying here and if it's not on your side I'll happily send another issue on the other side.

## Steps to reproduce

1. Reload the page.
2. Try to paste an image on a new post or on an answer of a _public_ discussion. It should work.
3. Try to paste an image as a reply of a private discussion. It should redirect you back to the last public post you were on (I suppose).
4. Try to paste images everywhere: it no longer works, but from private message there is no more redirections.
5. Reload the page: everything is now back to normal.

## Flarum info

<details><summary><code>php flarum info</code></summary>
<pre>$ php flarum info
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Flarum core 0.1.0-beta.10
PHP version: 7.3.10
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, imagick, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, zip, Phar, Zend OPcache
+------------------------------+----------------+--------+
| Flarum Extensions            |                |        |
+------------------------------+----------------+--------+
| ID                           | Version        | Commit |
+------------------------------+----------------+--------+
| flarum-approval              | v0.1.0-beta.8  |        |
| flarum-bbcode                | v0.1.0-beta.8  |        |
| flarum-emoji                 | v0.1.0-beta.10 |        |
| flarum-flags                 | v0.1.0-beta.9  |        |
| flarum-likes                 | v0.1.0-beta.9  |        |
| flarum-lock                  | v0.1.0-beta.9  |        |
| flarum-markdown              | v0.1.0-beta.10 |        |
| flarum-mentions              | v0.1.0-beta.10 |        |
| flarum-sticky                | v0.1.0-beta.9  |        |
| flarum-subscriptions         | v0.1.0-beta.9  |        |
| flarum-suspend               | v0.1.0-beta.9  |        |
| flarum-tags                  | v0.1.0-beta.10 |        |
| flarum-lang-english          | v0.1.0-beta.10 |        |
| flarum-statistics            | v0.1.0-beta.9  |        |
| extiverse-bazaar             | 0.4.0          |        |
| fof-user-bio                 | 0.1.3          |        |
| milescellar-lang-french      | v1.4.1         |        |
| rooaaar-lang-french-extended | v1.13.0        |        |
| reflar-nightmode             | 0.2.0          |        |
| fof-split                    | 0.4.3          |        |
| amaurycarrade-syndication    | v0.2.0         |        |
| fof-merge-discussions        | 0.3.3          |        |
| flagrow-upload               | 0.7.1          |        |
| fof-transliterator           | 0.2.0          |        |
| flagrow-direct-links         | 0.2.0          |        |
| fof-links                    | 0.2.1          |        |
| fof-formatting               | 0.1.2          |        |
| flagrow-sitemap              | 0.2.0          |        |
| kvothe-keyboard-shortcuts    | v0.1.0         |        |
| fof-user-directory           | 0.3.3          |        |
| fof-spamblock                | 0.2.1          |        |
| fof-socialprofile            | 0.1.1          |        |
| v17development-seo           | 1.0.2          |        |
| fof-byobu                    | 0.3.4          |        |
+------------------------------+----------------+--------+
Base URL: https://forum.zcraft.fr
Installation path: /home/www/zcraft/forum
Debug mode: off
</pre>
</details>

**Comment by davwheat** [comment]
Can almost certainly reproduce

Example of a live site with the issue https://community.giffgaff.com/ :P

**Comment by luceos** [comment]
Don't have the time to jump onto this, does any of you have any idea where it might come from?

**Comment by imorland** [comment]
@davwheat is this still an issue on giffgaff? I can't remember off the top of my head

**Comment by davwheat** [comment]
@imorland 

It definitely was but I haven't noticed it in the past few days. I'll do some testing.

**Comment by imorland** [comment]
I have a suspicion that now we've updated to `fof/upload 0.8.0` this is now solved, but want to be sure

**Comment by imorland** [comment]
Tested on https://preview.community.giffgaff.com/ - using `0.8.0` of `fof/upload` and `byobu` `0.3.4` and it appears to be fine.

Is this still an issue for you @AmauryCarrade ?
