### ISSUE TITLE
Can’t add additional recipients

### ISSUE THREAD

**Issue by katosdev** [FriendsOfFlarum/byobu#88]
When trying to amend the recipients I receive a red alert saying that you do not have permissions. Happens on discuss.flarum.org

Steps to reproduce:

1. Create a discussion to a user and include the mods user group.
2. Go back to the discussion and add a second user (e.g. jordanjay)
3. Save changes, and error appears.

This has not been verified as an extension issue and I will grab more details for the issue later.

**Comment by clarkwinkelmann** [comment]
Could it be related to #70 ? Though I don't think any mod/admin blocked PMs as we only use byobu ourselves anyway.

**Comment by katosdev** [comment]
Further to the original post, further investigation shows the following in the console on failure:

![image](https://user-images.githubusercontent.com/7927609/71523653-da085600-28c1-11ea-8385-909b12339d96.png)

**Comment by katosdev** [comment]
> Could it be related to #70 ? Though I don't think any mod/admin blocked PMs as we only use byobu ourselves anyway.

Hmm, possible. Maybe if the user in question suddenly blocked the rights to privately message, this could also throw the exception?

**Comment by luceos** [comment]
Additional user does not block pd. User permission (mods) is set up correctly for tag.

**Comment by Ornanovitch** [comment]
Have exactly the same issue here, but nothing related with #70 (all users of my discussion are allowing PM)

**Comment by Ornanovitch** [comment]
Does anybody has try to reproduce since beta 15 ?

**Comment by Ornanovitch** [comment]
I tested beta 15, it seems fixed for me !

**Comment by davwheat** [comment]
Can't reproduce in 1.0 stable.
