### ISSUE TITLE
"Oops! Something went wrong." while posting

### ISSUE THREAD

**Issue by hrvoje-hr** [FriendsOfFlarum/byobu#93]
Installed the latest dev-master build with merged all latest PRs by @imorland and other GG devs.

While everything works as on GiffGaff (except still needed to use tags) , _"Oops! Something went wrong. Please reload the page and try again."_ error appears when the user tries to open private discussion or reply to the existing one.

While the mentioned error appears, in the background discussion or reply is still successfully posted.

Tested on the latest Chrome and Firefox across two Flarum instances.

![2020-02-18 13_10_27-dasdasd - FFA hr Forum](https://user-images.githubusercontent.com/58295114/74735027-23d14500-5250-11ea-90d4-79fa76b2687a.png)

**Comment by imorland** [comment]
I’m aware of this issue, hence why a new tag version was not released. Not had a chance to look at the underlying cause, so any debug information you can share will be very useful

**Comment by hrvoje-hr** [comment]
Chrome says 500 (Internal Server Error) with reference on mithril.js file on line 2191

```
		if (data && !isString(data) && data.constructor !== global.FormData) {
			throw new Error("Request data should be either be a string or " +
				"FormData. Check the `serialize` option in `m.request`")
		}

		xhr.send(data)
		return xhr
	}
```
Tried all of the bellow, but the error still persists:
- disable all other extensions
- change tags
- add and remove recipients
- send messages between all basic groups only
- change discussion title

**Comment by imorland** [comment]
@hrvoje-hr can you try updating to the latest `dev-master` please? I found and fixed an issue that _may_ be causing this...

**Comment by hrvoje-hr** [comment]
I did. Unfortunately still the same at me.  The same error in console.

**Comment by imorland** [comment]
Thanks for checking @hrvoje-hr 

Perhaps could you please try
- disable the extension
- clear the cache
- enable the extension
- clear browser cache
- try again?

If it still does not work for you, can you maybe enable debug mode from `config.php` and share the error produced?

**Comment by hrvoje-hr** [comment]
It's the same after all steps. Here is the error from the debug mode:

`500 Internal Server Error
POST http://localhost/forum/public/api/posts

{
  "errors": [
    {
      "status": "500",
      "code": "unknown",
      "detail": "Swift_TransportException: Process could not be started [The system cannot find the path specified.\r\n] in C:\\xampp\\htdocs\\forum\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\StreamBuffer.php:302\nStack trace:\n#0 C:\\xampp\\htdocs\\forum\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\StreamBuffer.php(54): Swift_Transport_StreamBuffer->establishProcessConnection()\n#1 C:\\xampp\\htdocs\\forum\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)\n#2 C:\\xampp\\htdocs\\forum\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()\n#3 C:\\xampp\\htdocs\\forum\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mailer.php(65): Swift_Transport_SendmailTransport->start()\n#4 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\mail\\Mailer.php(483): Swift_Mailer->send(Object(Swift_Message), Array)\n#5 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\mail\\Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))\n#6 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Notification\\NotificationMailer.php(43): Illuminate\\Mail\\Mailer->send(NULL, Array, Object(Closure))\n#7 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Notification\\NotificationSyncer.php(200): Flarum\\Notification\\NotificationMailer->send(Object(FoF\\Byobu\\Notifications\\DiscussionRepliedBlueprint), Object(Flarum\\User\\User))\n#8 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Notification\\NotificationSyncer.php(186): Flarum\\Notification\\NotificationSyncer->mailNotifications(Object(FoF\\Byobu\\Notifications\\DiscussionRepliedBlueprint), Array)\n#9 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Notification\\NotificationSyncer.php(118): Flarum\\Notification\\NotificationSyncer->sendNotifications(Object(FoF\\Byobu\\Notifications\\DiscussionRepliedBlueprint), Array)\n#10 C:\\xampp\\htdocs\\forum\\vendor\\fof\\byobu\\src\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion.php(53): Flarum\\Notification\\NotificationSyncer->sync(Object(FoF\\Byobu\\Notifications\\DiscussionRepliedBlueprint), Array)\n#11 [internal function]: FoF\\Byobu\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion->handle(Object(Flarum\\Notification\\NotificationSyncer))\n#12 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\container\\BoundMethod.php(29): call_user_func_array(Array, Array)\n#13 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#14 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Flarum\\Foundation\\Application), Array, Object(Closure))\n#15 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\container\\Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Flarum\\Foundation\\Application), Array, Array, NULL)\n#16 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\bus\\Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)\n#17 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(FoF\\Byobu\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion))\n#18 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\pipeline\\Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(FoF\\Byobu\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion))\n#19 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#20 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\queue\\CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(FoF\\Byobu\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion), false)\n#21 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\queue\\Jobs\\Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)\n#22 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\queue\\SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()\n#23 C:\\xampp\\htdocs\\forum\\vendor\\fof\\byobu\\src\\Listeners\\QueueNotificationJobs.php(41): Illuminate\\Queue\\SyncQueue->push(Object(FoF\\Byobu\\Jobs\\SendNotificationWhenPostedInPrivateDiscussion))\n#24 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Database\\AbstractModel.php(58): FoF\\Byobu\\Listeners\\QueueNotificationJobs->FoF\\Byobu\\Listeners\\{closure}(Object(Flarum\\Post\\CommentPost))\n#25 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\events\\Dispatcher.php(360): Flarum\\Database\\AbstractModel::Flarum\\Database\\{closure}(Object(Flarum\\Post\\CommentPost))\n#26 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\events\\Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.saved:...', Array)\n#27 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\database\\Eloquent\\Concerns\\HasEvents.php(162): Illuminate\\Events\\Dispatcher->dispatch('eloquent.saved:...', Array)\n#28 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\database\\Eloquent\\Model.php(692): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('saved', false)\n#29 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\database\\Eloquent\\Model.php(663): Illuminate\\Database\\Eloquent\\Model->finishSave(Array)\n#30 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Post\\Command\\PostReplyHandler.php(103): Illuminate\\Database\\Eloquent\\Model->save()\n#31 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\bus\\Dispatcher.php(90): Flarum\\Post\\Command\\PostReplyHandler->handle(Object(Flarum\\Post\\Command\\PostReply))\n#32 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Flarum\\Post\\Command\\PostReply))\n#33 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\pipeline\\Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Flarum\\Post\\Command\\PostReply))\n#34 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#35 C:\\xampp\\htdocs\\forum\\vendor\\illuminate\\bus\\Dispatcher.php(76): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Flarum\\Post\\Command\\PostReply))\n#36 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Api\\Controller\\CreatePostController.php(73): Illuminate\\Bus\\Dispatcher->dispatch(Object(Flarum\\Post\\Command\\PostReply))\n#37 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Api\\Controller\\AbstractSerializeController.php(96): Flarum\\Api\\Controller\\CreatePostController->data(Object(Zend\\Diactoros\\ServerRequest), Object(Tobscure\\JsonApi\\Document))\n#38 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Api\\Controller\\AbstractCreateController.php(22): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#39 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractCreateController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#40 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}(Object(Zend\\Diactoros\\ServerRequest), Array)\n#41 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\DispatchRoute->process(Object(Zend\\Diactoros\\ServerRequest), Object(Closure))\n#42 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\SetLocale.php(50): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#43 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\SetLocale->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#44 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\CheckCsrfToken.php(31): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#45 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\CheckCsrfToken->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#46 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\AuthenticateWithHeader.php(55): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#47 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#48 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\AuthenticateWithSession.php(32): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#49 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#50 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\RememberFromCookie.php(51): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#51 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\RememberFromCookie->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#52 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\StartSession.php(61): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#53 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\StartSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#54 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Api\\Middleware\\FakeHttpMethods.php(29): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#55 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Api\\Middleware\\FakeHttpMethods->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#56 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\ParseJsonBody.php(28): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#57 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\ParseJsonBody->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#58 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Middleware\\HandleErrors.php(57): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#59 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Flarum\\Http\\Middleware\\HandleErrors->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#60 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#61 C:\\xampp\\htdocs\\forum\\vendor\\middlewares\\request-handler\\src\\RequestHandler.php(84): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#62 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Middlewares\\RequestHandler->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#63 C:\\xampp\\htdocs\\forum\\vendor\\middlewares\\base-path-router\\src\\BasePathRouter.php(97): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#64 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Middlewares\\BasePathRouter->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#65 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Middleware\\OriginalMessages.php(41): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#66 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Zend\\Stratigility\\Middleware\\OriginalMessages->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#67 C:\\xampp\\htdocs\\forum\\vendor\\middlewares\\base-path\\src\\BasePath.php(53): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#68 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\Next.php(60): Middlewares\\BasePath->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#69 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#70 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-stratigility\\src\\MiddlewarePipe.php(72): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\EmptyPipelineHandler))\n#71 C:\\xampp\\htdocs\\forum\\vendor\\zendframework\\zend-httphandlerrunner\\src\\RequestHandlerRunner.php(95): Zend\\Stratigility\\MiddlewarePipe->handle(Object(Zend\\Diactoros\\ServerRequest))\n#72 C:\\xampp\\htdocs\\forum\\vendor\\flarum\\core\\src\\Http\\Server.php(44): Zend\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#73 C:\\xampp\\htdocs\\forum\\public\\index.php(22): Flarum\\Http\\Server->listen()\n#74 {main}"
    }
  ]
}`

**Comment by hrvoje-hr** [comment]
That's it, it must be something with mailing. That was on my local Flarum instance without configured mail settings.

I just tried it on the server with everything configured and it went well without any errors.

**Comment by imorland** [comment]
That's great, thanks @hrvoje-hr 

I'm glad that it's now working for you. In regards to this specific error, I'm going to close this issue, as I believe that [this core issue](https://github.com/flarum/core/issues/1808) will ultimately solve the mis/unconfigured mail driver.
