### ISSUE TITLE
Invalid translations string

### ISSUE THREAD

**Issue by rob006** [FriendsOfFlarum/byobu#94]
https://github.com/FriendsOfFlarum/byobu/blob/d002f4ded38dcbcedf4fd17f04fa5c0f53803ebb/resources/locale/en.yml#L19

Shouldn't this be plural: "Private discussions"?

**Comment by imorland** [comment]
Hmm, looks like this key is not currently used by anything. Perhaps a throwback to something @luceos was/is planning?

**Comment by luceos** [comment]
No idea, feel free to drop it if not found in the source.
