### ISSUE TITLE
Can't add members with 2-character usernames

### ISSUE THREAD

**Issue by noriods** [FriendsOfFlarum/byobu#96]
My main moderator has a username that's just 2 characters long. As a result, I can't add him to a private discussion because byobu expects 3 characters before it will start searching members.

**Comment by imorland** [comment]
In general, Flarum will only handle searches, for usernames 3 characters and over.

The reason behind this is down to performance, whilst a lower character limit would be fine on forums with a relatively small amount of users, for large and mega forums, this would present a wide variety of issues.
