### ISSUE TITLE
Error on going to "Private Discussions" page.

### ISSUE THREAD

**Issue by askvortsov1** [FriendsOfFlarum/byobu#99]
Not exactly sure what's going on here, but I'm getting the following error:

GET https://forum.youthneuro.org/api/discussions?include=user%2ClastPostedUser%2CmostRelevantPost%2CmostRelevantPost.user%2CfirstPost%2Ctags%2CrecipientUsers%2CrecipientGroups%2Cpoll%2ClatestViews&filter%5Bq%5D=byobu%3Aaskvortsov%20is%3Aprivate&sort=-lastPostedAt&

{
  "errors": [
    {
      "status": "500",
      "code": "unknown",
      "detail": "PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in where clause is ambiguous in /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select `flarum_...', Array)\n#1 /flarum/app/vendor/illuminate/database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select `flarum_...')\n#2 /flarum/app/vendor/illuminate/database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select `flarum_...', Array)\n#3 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `flarum_...', Array, Object(Closure))\n#4 /flarum/app/vendor/illuminate/database/Connection.php(333): Illuminate\\Database\\Connection->run('select `flarum_...', Array, Object(Closure))\n#5 /flarum/app/vendor/illuminate/database/Query/Builder.php(2095): Illuminate\\Database\\Connection->select('select `flarum_...', Array, true)\n#6 /flarum/app/vendor/illuminate/database/Query/Builder.php(2083): Illuminate\\Database\\Query\\Builder->runSelect()\n#7 /flarum/app/vendor/illuminate/database/Query/Builder.php(2569): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#8 /flarum/app/vendor/illuminate/database/Query/Builder.php(2084): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))\n#9 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)\n#10 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)\n#11 /flarum/app/vendor/flarum/core/src/Discussion/Search/DiscussionSearcher.php(79): Illuminate\\Database\\Eloquent\\Builder->get()\n#12 /flarum/app/vendor/flarum/core/src/Api/Controller/ListDiscussionsController.php(86): Flarum\\Discussion\\Search\\DiscussionSearcher->search(Object(Flarum\\Search\\SearchCriteria), 20, 0)\n#13 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListDiscussionsController->data(Object(Zend\\Diactoros\\ServerRequest), Object(Tobscure\\JsonApi\\Document))\n#14 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#15 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}(Object(Zend\\Diactoros\\ServerRequest), Array)\n#16 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\DispatchRoute->process(Object(Zend\\Diactoros\\ServerRequest), Object(Closure))\n#17 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#18 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\SetLocale->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#19 /flarum/app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#20 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\CheckCsrfToken->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#21 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#22 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#23 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#24 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#25 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#26 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\RememberFromCookie->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#27 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#28 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\StartSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#29 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#30 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Api\\Middleware\\FakeHttpMethods->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#31 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#32 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\ParseJsonBody->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#33 /flarum/app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#34 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\HandleErrors->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#35 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#36 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#37 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\RequestHandler->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#38 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#39 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePathRouter->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#40 /flarum/app/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#41 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\\Stratigility\\Middleware\\OriginalMessages->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#42 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#43 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePath->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#44 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#45 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\EmptyPipelineHandler))\n#46 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\\Stratigility\\MiddlewarePipe->handle(Object(Zend\\Diactoros\\ServerRequest))\n#47 /flarum/app/vendor/flarum/core/src/Http/Server.php(44): Zend\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#48 /flarum/app/public/index.php(22): Flarum\\Http\\Server->listen()\n#49 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in where clause is ambiguous in /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63\nStack trace:\n#0 /flarum/app/vendor/illuminate/database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select `flarum_...')\n#1 /flarum/app/vendor/illuminate/database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select `flarum_...', Array)\n#2 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `flarum_...', Array, Object(Closure))\n#3 /flarum/app/vendor/illuminate/database/Connection.php(333): Illuminate\\Database\\Connection->run('select `flarum_...', Array, Object(Closure))\n#4 /flarum/app/vendor/illuminate/database/Query/Builder.php(2095): Illuminate\\Database\\Connection->select('select `flarum_...', Array, true)\n#5 /flarum/app/vendor/illuminate/database/Query/Builder.php(2083): Illuminate\\Database\\Query\\Builder->runSelect()\n#6 /flarum/app/vendor/illuminate/database/Query/Builder.php(2569): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#7 /flarum/app/vendor/illuminate/database/Query/Builder.php(2084): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))\n#8 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)\n#9 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)\n#10 /flarum/app/vendor/flarum/core/src/Discussion/Search/DiscussionSearcher.php(79): Illuminate\\Database\\Eloquent\\Builder->get()\n#11 /flarum/app/vendor/flarum/core/src/Api/Controller/ListDiscussionsController.php(86): Flarum\\Discussion\\Search\\DiscussionSearcher->search(Object(Flarum\\Search\\SearchCriteria), 20, 0)\n#12 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListDiscussionsController->data(Object(Zend\\Diactoros\\ServerRequest), Object(Tobscure\\JsonApi\\Document))\n#13 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#14 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}(Object(Zend\\Diactoros\\ServerRequest), Array)\n#15 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\DispatchRoute->process(Object(Zend\\Diactoros\\ServerRequest), Object(Closure))\n#16 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#17 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\SetLocale->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#18 /flarum/app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#19 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\CheckCsrfToken->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#20 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#21 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#23 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#25 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\RememberFromCookie->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#26 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#27 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\StartSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#28 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#29 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Api\\Middleware\\FakeHttpMethods->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#30 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#31 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\ParseJsonBody->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#32 /flarum/app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#33 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\HandleErrors->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#34 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#35 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#36 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\RequestHandler->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#37 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#38 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePathRouter->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#39 /flarum/app/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#40 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\\Stratigility\\Middleware\\OriginalMessages->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#41 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#42 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePath->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#43 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#44 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\EmptyPipelineHandler))\n#45 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\\Stratigility\\MiddlewarePipe->handle(Object(Zend\\Diactoros\\ServerRequest))\n#46 /flarum/app/vendor/flarum/core/src/Http/Server.php(44): Zend\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#47 /flarum/app/public/index.php(22): Flarum\\Http\\Server->listen()\n#48 {main}\n\nNext Illuminate\\Database\\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in where clause is ambiguous (SQL: select `flarum_discussions`.* from `flarum_discussions` inner join `flarum_recipients` on `flarum_discussions`.`id` = `flarum_recipients`.`discussion_id` where (not exists (select 1 from `flarum_discussion_tag` where 0 = 1 and `flarum_discussions`.`id` = `discussion_id`) or `user_id` = 2 and (`flarum_discussions`.`is_private` = 0 or (`flarum_discussions`.`is_approved` = 0 or `flarum_discussions`.`id` in (select `discussion_id` from `flarum_recipients` where `removed_at` is null and `user_id` = 2 or `group_id` in (1)) or `flarum_discussions`.`id` in (select `flarum_posts`.`discussion_id` from `flarum_flags` left join `flarum_posts` on `flarum_flags`.`post_id` = `flarum_posts`.`id`)))) and (`flarum_recipients`.`user_id` in (2) or `flarum_recipients`.`group_id` in (1)) and (exists (select 1 from `flarum_recipients` where `flarum_discussions`.`id` = discussion_id and `removed_at` is null and (`user_id` = 2 or `group_id` in (1)))) order by `last_posted_at` desc limit 21) in /flarum/app/vendor/illuminate/database/Connection.php:664\nStack trace:\n#0 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `flarum_...', Array, Object(Closure))\n#1 /flarum/app/vendor/illuminate/database/Connection.php(333): Illuminate\\Database\\Connection->run('select `flarum_...', Array, Object(Closure))\n#2 /flarum/app/vendor/illuminate/database/Query/Builder.php(2095): Illuminate\\Database\\Connection->select('select `flarum_...', Array, true)\n#3 /flarum/app/vendor/illuminate/database/Query/Builder.php(2083): Illuminate\\Database\\Query\\Builder->runSelect()\n#4 /flarum/app/vendor/illuminate/database/Query/Builder.php(2569): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#5 /flarum/app/vendor/illuminate/database/Query/Builder.php(2084): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))\n#6 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)\n#7 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)\n#8 /flarum/app/vendor/flarum/core/src/Discussion/Search/DiscussionSearcher.php(79): Illuminate\\Database\\Eloquent\\Builder->get()\n#9 /flarum/app/vendor/flarum/core/src/Api/Controller/ListDiscussionsController.php(86): Flarum\\Discussion\\Search\\DiscussionSearcher->search(Object(Flarum\\Search\\SearchCriteria), 20, 0)\n#10 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListDiscussionsController->data(Object(Zend\\Diactoros\\ServerRequest), Object(Tobscure\\JsonApi\\Document))\n#11 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#12 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}(Object(Zend\\Diactoros\\ServerRequest), Array)\n#13 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\DispatchRoute->process(Object(Zend\\Diactoros\\ServerRequest), Object(Closure))\n#14 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#15 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\SetLocale->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#16 /flarum/app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#17 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\CheckCsrfToken->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#18 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#19 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#20 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#21 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#23 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\RememberFromCookie->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#25 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\StartSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#26 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#27 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Api\\Middleware\\FakeHttpMethods->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#28 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#29 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\ParseJsonBody->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#30 /flarum/app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#31 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\HandleErrors->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#32 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#33 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#34 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\RequestHandler->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#35 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#36 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePathRouter->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#37 /flarum/app/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#38 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\\Stratigility\\Middleware\\OriginalMessages->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#39 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#40 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePath->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#41 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#42 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\EmptyPipelineHandler))\n#43 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\\Stratigility\\MiddlewarePipe->handle(Object(Zend\\Diactoros\\ServerRequest))\n#44 /flarum/app/vendor/flarum/core/src/Http/Server.php(44): Zend\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#45 /flarum/app/public/index.php(22): Flarum\\Http\\Server->listen()\n#46 {main}"
    }
  ]
}

**Comment by imorland** [comment]
@askvortsov1  is this using the latest release?

**Comment by askvortsov1** [comment]
After further testing, this seems to be caused by an extension conflict. Apologies for the confusion

**Comment by imorland** [comment]
No problem 😊
